package com.qwqnoi.community.mapper;

import com.qwqnoi.community.model.Usr;
import com.qwqnoi.community.model.UsrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UsrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Sun Feb 09 20:11:00 CST 2020
     */
    long countByExample(UsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Sun Feb 09 20:11:00 CST 2020
     */
    int deleteByExample(UsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Sun Feb 09 20:11:00 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Sun Feb 09 20:11:00 CST 2020
     */
    int insert(Usr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Sun Feb 09 20:11:00 CST 2020
     */
    int insertSelective(Usr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Sun Feb 09 20:11:00 CST 2020
     */
    List<Usr> selectByExampleWithRowbounds(UsrExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Sun Feb 09 20:11:00 CST 2020
     */
    List<Usr> selectByExample(UsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Sun Feb 09 20:11:00 CST 2020
     */
    Usr selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Sun Feb 09 20:11:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") Usr record, @Param("example") UsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Sun Feb 09 20:11:00 CST 2020
     */
    int updateByExample(@Param("record") Usr record, @Param("example") UsrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Sun Feb 09 20:11:00 CST 2020
     */
    int updateByPrimaryKeySelective(Usr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr
     *
     * @mbg.generated Sun Feb 09 20:11:00 CST 2020
     */
    int updateByPrimaryKey(Usr record);
}